project_id = "hnnlhddnettfaapyjggx"

[functions.send-chat-notification]
verify_jwt = true

[functions.send-review-notification]
verify_jwt = false

[functions.send-lead-email]
verify_jwt = false

[functions.send-followup-emails]
verify_jwt = false

[functions.generate-leads]
verify_jwt = true
