project_id = "hnnlhddnettfaapyjggx"

[functions.send-chat-notification]
verify_jwt = true

[functions.send-review-notification]
verify_jwt = false

[functions.send-lead-email]
verify_jwt = false

[functions.send-followup-emails]
verify_jwt = false

[functions.generate-leads]
verify_jwt = true

[functions.track-email]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.chat-ai-respond]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = false

[functions.auto-publish-blog]
verify_jwt = false

[functions.generate-blog-sitemap]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false
